config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products, only: :index do
    resources :bids, only: :create 
    collection do 
      get 'winners'
    end  
  end

  root 'products#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bid.rb
class Bid < ActiveRecord::Base  
  belongs_to :user
  belongs_to :product
  validates_presence_of :user
  validates_presence_of :product 
  validate :consecutive, on: :create
  validate :product_expired, on: :create

  def consecutive
    return if self.product.nil?
    return if self.product.bids.empty?

    if self.user_id == self.product.bids.last.user_id
      errors.add(:consecutive, "cannot bid twice in consecutive") 
    end
  end

  def product_expired
    return if self.product.nil?
    self.created_at ||= Time.now #fix for time before save
    if self.created_at >= self.product.expiration_time 
      errors.add(:expired, "cannot bid if product is expired") 
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :photo
  validates_presence_of :price
  has_many :bids, :dependent => :destroy

  def time_left
    left = (self.expiration_time - Time.now).seconds.to_i
    left = 0 if left <= 0  
    return left
  end

  def expiration_time
    created_at + 2.hours + self.bids.count * 2.minutes
  end

  def expired?
    return Time.now >= self.expiration_time
  end

  def current_price
    self.price + self.bids.count 
  end

  def winner
    if self.bids.empty?
      return "no hay ganador"
    else
      return self.bids.last.user.email
    end      

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bids
  has_many :products, through: :bids
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def create
    @products = Product.all
    @product = Product.find(params[:product_id])
    @bid = Bid.new(product: @product, user: current_user)
    @bid.save
    
    respond_to do |f|
      f.html
      f.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def bids_params
    params.require(:bid).permit(:name)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes(:bids)
  end

  def winners
    # This could be improved filtering expired products
    @products = Product.includes(:bids)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/bids/create.html.erb
<h1>Bids#create</h1>
<p>Find me in app/views/bids/create.html.erb</p>

app/views/bids/create.js.erb
$("#products").html("<%= j render @products %>")
if (<%= @bid.valid? %> == false)
{
	$(".alert").html("No puedes agregar dos veces consecutivas o ofertar después del plazo")
}

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Prueba final</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= products_path %>">Productos <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= winners_products_path %>">Ganadores</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="<%= destroy_user_session_path %>" data-method="delete">Salir</a></li>
        <% else %>
          <li><a href="<%= new_user_session_path %>">Ingresar</a></li>
          <li><a href="<%= new_user_registration_path %>">Registrarse</a></li>
        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pauta</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</head>
<body>
	<%= render 'layouts/navbar' %>


<div class="container">       
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

	<%= yield %>
</div>

</body>
</html>

app/views/products/_product.html.erb
<div class="col-md-6">
<div class="well">
	<div class="row">
		<div class="col-md-4">
		<%= image_tag (product.photo), class: "img-thumbnail" %>
		</div>

		<div class="col-md-8">
		<h3><%= product.name %> </h3>
		<h4> Precio: <%= product.current_price %> </h4>	
		<p class="limit-time">
			<%= product.time_left %>
		</p>
	<%= link_to "Ofertar", product_bids_path(product), method: "post", remote:true , class:"btn btn-primary" %>

	<h5> Últimas ofertas </h5>
	<ul>	
		<% product.bids.reverse.each do |b| %>
		<li><%= b.user.email %></li>
		<% end %>
	</ul>

		</div>

	</div>


</div>
</div>

app/views/products/index.html.erb
<div id="products">
	<%= render @products %>
</div>

app/views/products/winners.html.erb
<table class="table"> 
	<tr>
		<th> Producto </th>
		<th> Ganador </th>
	</tr>

<% @products.all.each do |product| %>
	<% if product.expired? %> 
	<tr> 
		<td> <%= product.name %> </td>
		<td> <%= product.winner %> </td>
	</tr>
	<% end %>
<% end %>
</table>